name: LAPRAS Card

on:
  workflow_dispatch:

jobs:
  update-card:
    name: LAPRAS Card
    runs-on: ubuntu-22.04
    steps:
      - uses: kawamataryo/lapras-card-readme@v1.2.1
        with:
          SHARE_ID: jtitor
          ICON_FIRST: "#212121"
          ICON_SECOND: "#818181"
          BACKGROUND_FIRST: "#232323"
          BACKGROUND_SECOND: "#6d6d6d"
          LANG: "en"
          CARD_WIDTH: "40%"
          UPDATE_TIME: "false"
