name: foo
on:
  workflow_dispatch:

jobs:
  foo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: foo
        id: foo
        run: |
          echo "foo<<EOF" >> $GITHUB_OUTPUT
          echo "$(cat ./README.md)" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - run: echo "${{ steps.foo.outputs.foo }}"
