name: test workflow

on:
  workflow_dispatch:

concurrency: ${{ github.workflow }}

jobs:
  update-card:
    name: Rust Thanks Card
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: |
          sleep 60
          exit 0
