name: Test
on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: foo
      - uses: actions/checkout@v3
        with:
          ref: main
      - run: git diff foo..main --exit-code
