name: test workflow

on:
  workflow_dispatch:

concurrency: ${{ github.workflow }}

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: |
          git pull
          git show-ref
          sleep 30
          exit 0
