name: test workflow

on:
  workflow_dispatch:
    inputs:
      foo:
        required: false

jobs:
  test:
    name: Test job
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: |
          if ${{ github.event.inputs.foo == '' }}; then
            echo @${{ github.actor }}
          else
            echo ${{ github.event.inputs.foo }}
          fi
