name: test workflow

on:
  workflow_dispatch:
    inputs:
      foo:
        required: true
        default: ${{ github.actor }}

concurrency: ${{ github.workflow }}

jobs:
  test:
    name: Test job
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: echo "${{ github.event.inputs.foo }}"
