name: Rust Thanks Card

on:
  # Schedule monthly updates
  schedule:
    - cron: 0 0 1 * *
  workflow_dispatch:

jobs:
  update-card:
    name: Rust Thanks Card
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - id: rust-thanks
        uses: JohnTitor/rust-thanks-card@8441caa72c4ab17f1e627a2baed66d8a8fcbe4c4 # v0.2.0
        with:
          name: "Yuki Okushi"
          format: "badge"
          output-path: "assets/rust-thanks-card.svg"
          avatar-url: "https://avatars.githubusercontent.com/u/25030997?v=4"
          theme: "rust"
          write-readme: "true"
          push-changes: "true"
