name: Rust Thanks Card

on:
  # Schedule monthly updates
  schedule:
    - cron: 0 0 1 * *
  workflow_dispatch:

jobs:
  update-card:
    name: Rust Thanks Card
    runs-on: ubuntu-22.04
    steps:
      - uses: JohnTitor/rust-thanks-card@main
        with:
          name: 'Yuki Okushi'
          image_url: 'https://avatars.githubusercontent.com/u/25030997?v=4'
          type: 'badge'
